version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pm_app
      POSTGRES_HOST_AUTH_METHOD: trust
    restart: always
    volumes:
      - database-data:/var/lib/postgresql/data/
      - ./database/init-database.sh:/docker-entrypoint-initdb.d/init-database.sh
  prisma-studio:
    container_name: prisma-studio
    image: timothyjmiller/prisma-studio:latest
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - 5555:5555
    logging:
      driver: none
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: quantran2381@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 238200
      GUNICORN_ACCESS_LOGFILE: '/dev/null'
    ports:
      - '5050:80'
    env_file:
      - .env
    restart: always
    volumes:
      - pgadmin:/root/.pgadmin
    logging:
      driver: none
  backend:
    build: ./
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    links:
      - postgres
    command: 'npm run dev'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env

volumes:
  database-data:
  pgadmin:
